version: 2

build:
  os: ubuntu-latest
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py

formats:
  - pdf

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
