version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)
      - sed -i "s/{{VERSION_PLACEHOLDER}}/${READTHEDOCS_VERSION}/g" setup.py

sphinx:
  configuration: docs/conf.py

formats:
  - pdf

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
