from enum import IntEnum


class ID_TYPE(IntEnum):
    NONE = 0
    SENATE = 1
    CONTRACT_UPGRADE = 2
    __GAP__ = 3
    OPERATOR = 4
    POOL = 5
    LIMIT_DEFAULT_MODULE_MIN = 10000
    DEFAULT_MODULE_WITHDRAWAL_CONTRACT = 10011
    DEFAULT_MODULE_LIQUDITY_POOL = 10021
    DEFAULT_MODULE_LIQUDITY_POOL_TOKEN = 10022
    LIMIT_DEFAULT_MODULE_MAX = 19999
    LIMIT_ALLOWED_MODULE_MIN = 20000
    ALLOWED_MODULE_GETH_INTERFACE = 20031
    LIMIT_ALLOWED_MODULE_MAX = 29999
