name: Build and publish python 🐍 package 📦 to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Python 3.10
        uses: actions/setup-python@v5.1.1
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configure Poetry
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
      #   poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_TOKEN }}
      #   poetry config repositories.test-pypi https://test.pypi.org/legacy/
      - name: Publish to PyPI
        run: |
          poetry publish --build
      #   poetry publish --build -r test-pypi
